# NumPy: cours OpenClassrooms

NumPy est une lib qui permet d'effectuer rapidement et simplement des calculs complexes grâce aux Arrays.

In [17]:
import numpy as np

In [18]:
revenus = [1400, 1700, 2100, 3000, 6000, 550]

print("Moyenne des revenus : " + str(round(np.mean(revenus),2)) + " €")

Moyenne des revenus : 2458.33 €


`np.mean()` est une fonction de NumPy qui permet de calculer la moyenne.
Elle accepte aussi bien un array NumPy qu’une liste Python (ou tout objet array-like).

`.mean()` est une méthode de la classe ndarray (l’objet principal de NumPy). Elle ne peut être utilisée que sur un array NumPy.

In [21]:
revenus_moy = np.array(revenus).mean()

print(round(revenus_moy, 2))

2458.33


In [44]:
print(np.zeros(10))
print(np.ones(3))
print(np.arange(2, 12, 2))
print(np.linspace(1, 60, 5))
print(np.power(2, np.arange(1, 14)))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1.]
[ 2  4  6  8 10]
[ 1.   15.75 30.5  45.25 60.  ]
[   2    4    8   16   32   64  128  256  512 1024 2048 4096 8192]


In [45]:
revenus_moy.dtype

dtype('float64')

In [64]:
revenus_array = np.array(revenus)

In [65]:
revenus_array[0]

np.int64(1400)

In [70]:
print(revenus_array)
revenus_array[(revenus_array > 2000) & (revenus_array < 4000)]

[1400 1700 2100 3000 6000  550]


array([2100, 3000])

In [75]:
revenus_array.shape

(6,)

In [77]:
revenus_array.max()

np.int64(6000)

In [101]:
revenus_array.sort()
level = ["RSA", "SMIC", "Modeste", "Confortable", "Aisé", "Riche"]
for i, revenu in enumerate(revenus_array):
    print(level[i].rjust(15), str(revenu).rjust(4), "€")

            RSA  550 €
           SMIC 1400 €
        Modeste 1700 €
    Confortable 2100 €
           Aisé 3000 €
          Riche 6000 €


## Créer un tableau avec NumPy

In [103]:
hugo = [21, 1400, 0]
richard = [54, 2800, 2]
emilie = [27, 3700, 3]
tableau = [hugo, richard, emilie]
print(tableau)

[[21, 1400, 0], [54, 2800, 2], [27, 3700, 3]]


In [104]:
np.array(tableau)

array([[  21, 1400,    0],
       [  54, 2800,    2],
       [  27, 3700,    3]])

In [134]:
A = np.ones((3,5))
B = np.ones((3,5))
A + B

array([[2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.]])

In [111]:
print(np.random.randint(1, 10, size=(3, 5)))

[[5 9 6 3 7]
 [4 1 6 4 9]
 [6 4 9 9 5]]


### Calcul matriciel (A @ B) de deux matrices de taille 2:2

In [139]:
A = np.array([[2, -2], [5, 3]])
B = np.array([[-1, 4], [7, -6]])
A @ B

array([[-16,  20],
       [ 16,   2]])