# Pandas : Data frames

In [12]:
import pandas as pd
import numpy as np

In [5]:
data_csv = pd.read_csv("data/course.csv")
data_csv.head()

,✅,COURS,CHAPITRE,IMPORTANCE
0,FALSE,Algèbre linéaire,Vecteurs et espaces vectoriels,Accessoire
1,FALSE,Algèbre linéaire,Matrices d'applications linéaires,Accessoire
2,FALSE,Algèbre linéaire,Changement de système de coordonnées,Accessoire
3,FALSE,Statistiques et probabilités,Séries statistiques à caractère qualitatif,Indispensable
4,FALSE,Statistiques et probabilités,Représentation et comparaison de données quant...,Indispensable


In [6]:
data_excel = pd.read_excel("data/course.xlsx")
data_excel.tail(3)

,✅,COURS,CHAPITRE,IMPORTANCE
140,False,GitHub,Livrable final : Docker-compose (optionnel mai...,Bonus
141,False,GitHub,Livrable final : Capture d'écran du dashboard ...,Indispensable
142,NaN,NaN,0,NaN


In [7]:
data_csv.dtypes

✅             str
COURS         str
CHAPITRE      str
IMPORTANCE    str
dtype: object

### Convertir en array NumPy

In [8]:
data_array = data_csv.values
data_array[:5,:]

array([['FALSE', 'Algèbre linéaire', 'Vecteurs et espaces vectoriels',
        'Accessoire'],
       ['FALSE', 'Algèbre linéaire', "Matrices d'applications linéaires",
        'Accessoire'],
       ['FALSE', 'Algèbre linéaire',
        'Changement de système de coordonnées', 'Accessoire'],
       ['FALSE', 'Statistiques et probabilités',
        'Séries statistiques à caractère qualitatif', 'Indispensable'],
       ['FALSE', 'Statistiques et probabilités',
        'Représentation et comparaison de données quantitatives',
        'Indispensable']], dtype=object)

### Excercice : Table de Montessori

#### Version 1

In [35]:
n = 12

x = np.arange(1, n+1)
# [ 1  2  3  4  5  6  7  8  9 10 11 12]

y = np.arange(1, n+1)
# [ 1  2  3  4  5  6  7  8  9 10 11 12]

In [48]:
montessori_one = x[:, None] * y
# OU 
# x.reshape(10,1)

print(montessori_one)

[[  1   2   3   4   5   6   7   8   9  10  11  12]
 [  2   4   6   8  10  12  14  16  18  20  22  24]
 [  3   6   9  12  15  18  21  24  27  30  33  36]
 [  4   8  12  16  20  24  28  32  36  40  44  48]
 [  5  10  15  20  25  30  35  40  45  50  55  60]
 [  6  12  18  24  30  36  42  48  54  60  66  72]
 [  7  14  21  28  35  42  49  56  63  70  77  84]
 [  8  16  24  32  40  48  56  64  72  80  88  96]
 [  9  18  27  36  45  54  63  72  81  90  99 108]
 [ 10  20  30  40  50  60  70  80  90 100 110 120]
 [ 11  22  33  44  55  66  77  88  99 110 121 132]
 [ 12  24  36  48  60  72  84  96 108 120 132 144]]


#### Version 2 (plus rapide)

In [33]:
montessori_two = np.outer(x,y)

print(montessori_two)

[[  1   2   3   4   5   6   7   8   9  10  11  12]
 [  2   4   6   8  10  12  14  16  18  20  22  24]
 [  3   6   9  12  15  18  21  24  27  30  33  36]
 [  4   8  12  16  20  24  28  32  36  40  44  48]
 [  5  10  15  20  25  30  35  40  45  50  55  60]
 [  6  12  18  24  30  36  42  48  54  60  66  72]
 [  7  14  21  28  35  42  49  56  63  70  77  84]
 [  8  16  24  32  40  48  56  64  72  80  88  96]
 [  9  18  27  36  45  54  63  72  81  90  99 108]
 [ 10  20  30  40  50  60  70  80  90 100 110 120]
 [ 11  22  33  44  55  66  77  88  99 110 121 132]
 [ 12  24  36  48  60  72  84  96 108 120 132 144]]


#### Version 3

In [42]:
montessori_three = []

for i in range(1,11):
    row = []
    for j in range(1,11):
        row.append(i*j)
    montessori_three.append(row)

print(montessori_three)

[[1, 2, 3, 4, 5, 6, 7, 8, 9, 10], [2, 4, 6, 8, 10, 12, 14, 16, 18, 20], [3, 6, 9, 12, 15, 18, 21, 24, 27, 30], [4, 8, 12, 16, 20, 24, 28, 32, 36, 40], [5, 10, 15, 20, 25, 30, 35, 40, 45, 50], [6, 12, 18, 24, 30, 36, 42, 48, 54, 60], [7, 14, 21, 28, 35, 42, 49, 56, 63, 70], [8, 16, 24, 32, 40, 48, 56, 64, 72, 80], [9, 18, 27, 36, 45, 54, 63, 72, 81, 90], [10, 20, 30, 40, 50, 60, 70, 80, 90, 100]]


#### Créer un DataFrame pandas et l'exporter en Excel

In [45]:
df = pd.DataFrame(montessori_two, index=x, columns=y)
df

,1,2,3,4,5,6,7,8,9,10,11,12
1,1,2,3,4,5,6,7,8,9,10,11,12
2,2,4,6,8,10,12,14,16,18,20,22,24
3,3,6,9,12,15,18,21,24,27,30,33,36
4,4,8,12,16,20,24,28,32,36,40,44,48
5,5,10,15,20,25,30,35,40,45,50,55,60
6,6,12,18,24,30,36,42,48,54,60,66,72
7,7,14,21,28,35,42,49,56,63,70,77,84
8,8,16,24,32,40,48,56,64,72,80,88,96
9,9,18,27,36,45,54,63,72,81,90,99,108
10,10,20,30,40,50,60,70,80,90,100,110,120


In [49]:
df.to_excel("data/montessori.xlsx")

## Series

In [50]:
pd.Series([2,4,6,8])

0    2
1    4
2    6
3    8
dtype: int64

In [52]:
pd.Series([2,4,6,8], index=["a","b","c","d"])

a    2
b    4
c    6
d    8
dtype: int64

In [53]:
pd.Series([2,4,6,8], index=["a","b","c","d"], name="pair")

a    2
b    4
c    6
d    8
Name: pairs, dtype: int64

### Création d'un petit DataFrame en détail

In [59]:
pd.DataFrame({
"impair": [1,3,5,7],
"pair": [2,4,6,8]},
index=["a","b","c","d"]
)

,impair,pair
a,1,2
b,3,4
c,5,6
d,7,8


### Lecture de CSV de grande taille

In [67]:
bitcoin = pd.read_csv("data/btcusd_1-min_data.csv")
bitcoin.shape # important pour savoir la taille avant d'afficher

(7489124, 6)

In [68]:
bitcoin.tail()

,Timestamp,Open,High,Low,Close,Volume
7489119,1.774829e+09,65961.0,66020.0,65954.0,65995.0,5.834382
7489120,1.774829e+09,65995.0,65998.0,65905.0,65908.0,5.098770
7489121,1.774829e+09,65908.0,65926.0,65862.0,65862.0,1.399734
7489122,1.774829e+09,65848.0,65866.0,65836.0,65866.0,1.536226
7489123,1.774829e+09,65865.0,65865.0,65820.0,65820.0,3.313735


In [70]:
bitcoin.iloc[:,5]

0          0.000000
1          0.000000
2          0.000000
3          0.000000
4          0.000000
             ...   
7489119    5.834382
7489120    5.098770
7489121    1.399734
7489122    1.536226
7489123    3.313735
Name: Volume, Length: 7489124, dtype: float64

In [75]:
bitcoin.iloc[-1]

Timestamp    1.774829e+09
Open         6.586500e+04
High         6.586500e+04
Low          6.582000e+04
Close        6.582000e+04
Volume       3.313735e+00
Name: 7489123, dtype: float64

In [79]:
bitcoin.loc[:, ["High", "Low"]]

,High,Low
0,4.58,4.58
1,4.58,4.58
2,4.58,4.58
3,4.58,4.58
4,4.58,4.58
...,...,...
7489119,66020.00,65954.00
7489120,65998.00,65905.00
7489121,65926.00,65862.00
7489122,65866.00,65836.00


# Excercice pratique : Import then Select Data

In [81]:
work = pd.read_csv("data/work.csv")
work.head()

,DEBUT,FIN,SECTEUR,POSTE,RAISON SOCIALE,CONTRAT,Ville,DEPARTEMENT,REGION⚡
0,10/12/2025,13/12/2025,Audiovisuel / Spectacle / Cinéma,Régisseur adjoint (congrès national),Arkane Média,CDDU,Paris,75 - Paris,Île-de-France
1,01/11/2025,01/11/2025,Audiovisuel / Spectacle / Cinéma,Régisseur adjoint + acteur (court-métrage),CELESTIN Production,Bénévole,Paris,75 - Paris,Île-de-France
2,01/10/2025,01/10/2025,Audiovisuel / Spectacle / Cinéma,Assistant régisseur adjoint (série),KABO Family,CDDU,Dinard,22 - Côtes-d’Armor,Bretagne
3,01/07/2025,NaN,Hôtellerie / Restauration / Tourisme,Commis de cuisine,Le Quai 7,CDD,Dinan,22 - Côtes-d’Armor,Bretagne
4,01/04/2025,01/05/2025,Hôtellerie / Restauration / Tourisme,Serveur bar (Extras),Fluctuat Nec Mergitur,CDD,Paris 10,75 - Paris,Île-de-France


In [129]:
cdd = work.loc[work.CONTRAT.isin(["CDD", "CDDU", "Contrat d’intérim"])]
cdd

,DEBUT,FIN,SECTEUR,POSTE,RAISON SOCIALE,CONTRAT,Ville,DEPARTEMENT,REGION⚡
0,10/12/2025,13/12/2025,Audiovisuel / Spectacle / Cinéma,Régisseur adjoint (congrès national),Arkane Média,CDDU,Paris,75 - Paris,Île-de-France
2,01/10/2025,01/10/2025,Audiovisuel / Spectacle / Cinéma,Assistant régisseur adjoint (série),KABO Family,CDDU,Dinard,22 - Côtes-d’Armor,Bretagne
3,01/07/2025,NaN,Hôtellerie / Restauration / Tourisme,Commis de cuisine,Le Quai 7,CDD,Dinan,22 - Côtes-d’Armor,Bretagne
4,01/04/2025,01/05/2025,Hôtellerie / Restauration / Tourisme,Serveur bar (Extras),Fluctuat Nec Mergitur,CDD,Paris 10,75 - Paris,Île-de-France
14,28/10/2019,28/10/2019,Commerce / Vente,Inventoriste,Kiabi,Contrat d’intérim,Marmande,47 - Lot-et-Garonne,Nouvelle-Aquitaine
15,01/09/2019,NaN,Transport / Logistique,Agent de nettoyage,Axeo Services,Contrat d’intérim,Marmande,47 - Lot-et-Garonne,Nouvelle-Aquitaine
16,01/08/2019,01/09/2019,Transport / Logistique,Manutentionnaire,Axeo Services,Contrat d’intérim,Marmande,47 - Lot-et-Garonne,Nouvelle-Aquitaine
17,01/06/2019,01/07/2019,Audiovisuel / Spectacle / Cinéma,Assistant de régie,Garorock Experience,Contrat d’intérim,Marmande,47 - Lot-et-Garonne,Nouvelle-Aquitaine
18,01/01/2019,NaN,Hôtellerie / Restauration / Tourisme,Serveur banquets (Extras),Château de Lauquerie,CDD,Lauzun,47 - Lot-et-Garonne,Nouvelle-Aquitaine
19,01/01/2019,NaN,Hôtellerie / Restauration / Tourisme,2nd cuisine et serveur (Extras),Rod The Hog,CDD,St-Barthélemy d’Agenais,47 - Lot-et-Garonne,Nouvelle-Aquitaine


In [116]:
n = 47
dep = work.loc[work["DEPARTEMENT"].astype(str).str.startswith(str(n))]
dep

,DEBUT,FIN,SECTEUR,POSTE,RAISON SOCIALE,CONTRAT,Ville,DEPARTEMENT,REGION⚡
13,01/01/2020,NaN,Marketing / Communication,Graphiste & webdesigner (covid-19),Exclusive International Ballet Program,Freelance,Marmande,47 - Lot-et-Garonne,Nouvelle-Aquitaine
14,28/10/2019,28/10/2019,Commerce / Vente,Inventoriste,Kiabi,Contrat d’intérim,Marmande,47 - Lot-et-Garonne,Nouvelle-Aquitaine
15,01/09/2019,NaN,Transport / Logistique,Agent de nettoyage,Axeo Services,Contrat d’intérim,Marmande,47 - Lot-et-Garonne,Nouvelle-Aquitaine
16,01/08/2019,01/09/2019,Transport / Logistique,Manutentionnaire,Axeo Services,Contrat d’intérim,Marmande,47 - Lot-et-Garonne,Nouvelle-Aquitaine
17,01/06/2019,01/07/2019,Audiovisuel / Spectacle / Cinéma,Assistant de régie,Garorock Experience,Contrat d’intérim,Marmande,47 - Lot-et-Garonne,Nouvelle-Aquitaine
18,01/01/2019,NaN,Hôtellerie / Restauration / Tourisme,Serveur banquets (Extras),Château de Lauquerie,CDD,Lauzun,47 - Lot-et-Garonne,Nouvelle-Aquitaine
19,01/01/2019,NaN,Hôtellerie / Restauration / Tourisme,2nd cuisine et serveur (Extras),Rod The Hog,CDD,St-Barthélemy d’Agenais,47 - Lot-et-Garonne,Nouvelle-Aquitaine
21,01/01/2018,01/09/2020,Audiovisuel / Spectacle / Cinéma,"Régie plateau, régie lumière, régie générale","Tournées, concerts, spectacles",Freelance,NaN,47 - Lot-et-Garonne,Nouvelle-Aquitaine
22,01/01/2018,01/09/2020,Marketing / Communication,Infographiste,"Tournées, concerts, spectacles",Freelance,NaN,47 - Lot-et-Garonne,Nouvelle-Aquitaine
30,01/01/2013,NaN,Hôtellerie / Restauration / Tourisme,Équipier polyvalent de restauration,Mc Donald's,CDI,Marmande,47 - Lot-et-Garonne,Nouvelle-Aquitaine


In [135]:
work.loc[work.DEBUT.isnull() | work.FIN.isnull()]

,DEBUT,FIN,SECTEUR,POSTE,RAISON SOCIALE,CONTRAT,Ville,DEPARTEMENT,REGION⚡
3,01/07/2025,NaN,Hôtellerie / Restauration / Tourisme,Commis de cuisine,Le Quai 7,CDD,Dinan,22 - Côtes-d’Armor,Bretagne
5,01/01/2025,NaN,Audiovisuel / Spectacle / Cinéma,Directeur de production (court-métrage),CinéKastell,Bénévole,Dinan,22 - Côtes-d’Armor,Bretagne
6,01/01/2025,NaN,Audiovisuel / Spectacle / Cinéma,Régisseur général (court-métrage),CinéKastell,Bénévole,Dinan,22 - Côtes-d’Armor,Bretagne
7,01/03/2024,NaN,Informatique / IT,"Développeur Full Stack (Application ""WinPolar"")",Freelance,Freelance,Montpellier,34 - Hérault,Occitanie
8,01/12/2023,NaN,Informatique / IT,Développeur Back-end,One Point,Stage,Bordeaux,33 - Gironde,Nouvelle-Aquitaine
12,01/03/2020,NaN,Hôtellerie / Restauration / Tourisme,Commis de cuisine,Philippe Etchebest - Chaîne “Mentor”,Stage,Bordeaux,33 - Gironde,Nouvelle-Aquitaine
13,01/01/2020,NaN,Marketing / Communication,Graphiste & webdesigner (covid-19),Exclusive International Ballet Program,Freelance,Marmande,47 - Lot-et-Garonne,Nouvelle-Aquitaine
15,01/09/2019,NaN,Transport / Logistique,Agent de nettoyage,Axeo Services,Contrat d’intérim,Marmande,47 - Lot-et-Garonne,Nouvelle-Aquitaine
18,01/01/2019,NaN,Hôtellerie / Restauration / Tourisme,Serveur banquets (Extras),Château de Lauquerie,CDD,Lauzun,47 - Lot-et-Garonne,Nouvelle-Aquitaine
19,01/01/2019,NaN,Hôtellerie / Restauration / Tourisme,2nd cuisine et serveur (Extras),Rod The Hog,CDD,St-Barthélemy d’Agenais,47 - Lot-et-Garonne,Nouvelle-Aquitaine


In [138]:
work.loc[work.isna().any(axis=1)]

,DEBUT,FIN,SECTEUR,POSTE,RAISON SOCIALE,CONTRAT,Ville,DEPARTEMENT,REGION⚡
3,01/07/2025,NaN,Hôtellerie / Restauration / Tourisme,Commis de cuisine,Le Quai 7,CDD,Dinan,22 - Côtes-d’Armor,Bretagne
5,01/01/2025,NaN,Audiovisuel / Spectacle / Cinéma,Directeur de production (court-métrage),CinéKastell,Bénévole,Dinan,22 - Côtes-d’Armor,Bretagne
6,01/01/2025,NaN,Audiovisuel / Spectacle / Cinéma,Régisseur général (court-métrage),CinéKastell,Bénévole,Dinan,22 - Côtes-d’Armor,Bretagne
7,01/03/2024,NaN,Informatique / IT,"Développeur Full Stack (Application ""WinPolar"")",Freelance,Freelance,Montpellier,34 - Hérault,Occitanie
8,01/12/2023,NaN,Informatique / IT,Développeur Back-end,One Point,Stage,Bordeaux,33 - Gironde,Nouvelle-Aquitaine
12,01/03/2020,NaN,Hôtellerie / Restauration / Tourisme,Commis de cuisine,Philippe Etchebest - Chaîne “Mentor”,Stage,Bordeaux,33 - Gironde,Nouvelle-Aquitaine
13,01/01/2020,NaN,Marketing / Communication,Graphiste & webdesigner (covid-19),Exclusive International Ballet Program,Freelance,Marmande,47 - Lot-et-Garonne,Nouvelle-Aquitaine
15,01/09/2019,NaN,Transport / Logistique,Agent de nettoyage,Axeo Services,Contrat d’intérim,Marmande,47 - Lot-et-Garonne,Nouvelle-Aquitaine
18,01/01/2019,NaN,Hôtellerie / Restauration / Tourisme,Serveur banquets (Extras),Château de Lauquerie,CDD,Lauzun,47 - Lot-et-Garonne,Nouvelle-Aquitaine
19,01/01/2019,NaN,Hôtellerie / Restauration / Tourisme,2nd cuisine et serveur (Extras),Rod The Hog,CDD,St-Barthélemy d’Agenais,47 - Lot-et-Garonne,Nouvelle-Aquitaine


In [143]:
work["VILLE"] = range(len(work), 0, -1)

work["VILLE"]

0     36
1     35
2     34
3     33
4     32
5     31
6     30
7     29
8     28
9     27
10    26
11    25
12    24
13    23
14    22
15    21
16    20
17    19
18    18
19    17
20    16
21    15
22    14
23    13
24    12
25    11
26    10
27     9
28     8
29     7
30     6
31     5
32     4
33     3
34     2
35     1
Name: VILLE, dtype: int64